# Default Setting for Sleeper

is-animated: true
animation-speed: 125
animation-interval: 1

percentage-necessary-to-sleep: 0.25
ignored-players: []

rest-message: "title @a actionbar {\"text\":\"{actual} / {necessary} Players to skip night.\"}"
skip-night-message: "say Players skipped the night"
