name: Sleeper
main: me.bennypls.sleeper.Sleeper
version: 1.1.1
author: BennyPLS

commands:
  sleeper:
    description: Sleeper Plugin Administration
    usage: /sleeper help
    permission: sleeper.sleeper
    permission-message: You don't have permission.

permissions:
  sleeper:
    description: Manages Sleeper Plugin
    default: op
