name: Sleeper
main: me.bennypls.sleeper.Sleeper
version: '${project.version}'
author: BennyPLS

api-version: 1.19

commands:
  sleeper:
    description: Sleeper Plugin Administration
    usage: /sleeper help
    permission: sleeper.sleeper
    permission-message: You don't have permission.

permissions:
  sleeper:
    description: Manages Sleeper Plugin
    default: op
