name: Sleeper
main: me.bennypls.sleeper.Sleeper
version: 1.19.4-0.9.0
author: BennyPLS


commands:
  sleeper:
    description: This command is used for administrating the sleeper plugin with diferents arguments.
    usage: /sleeper <args>
    permission: sleeper.sleeper
    permission-message: You don't have permission.

permissions:
  sleeper:
    description: Manages Sleeper Plugin
    default: op